### ISSUE TITLE
Suggestion - hide install battlelog app message

### ISSUE THREAD

**Issue by TrigrH** [Battlelogium/Battlelogium#68]
This little message has to be manually closed every single time you want to use battlelog and it reduces the visible length of your friends list, even if you have the app installed this stupid popup still persists: ![](http://img673.imageshack.us/img673/263/jMLRJc.png)
Due to the style on the hardline page you can barely read it anyway:
![](http://img913.imageshack.us/img913/562/t4n9id.png)

**Comment by RonnChyran** [comment]
Fixed as of 2.2.11
