### ISSUE TITLE
2.2.11 installer crashes

### ISSUE THREAD

**Issue by koesie10** [Battlelogium/Battlelogium#72]
When installing Battlelogium, after the installer has downloaded Battlelogium, the installer crashes. I'm running Windows 8.1 64-bit with the Steam Beta.

I started a Visual Studio debug instance and the following error is shown:
```
Message: An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in mscorlib.dll

Additional information: Could not find a part of the path 'A:\Koen\Downloads\Battlelogium\locales\en-US.pak'.
```

I tried installing Battlelogium to `A:\Koen\Downloads\Battlelogium` in this instance.

I guess it has to do with the installer not properly creating all directories needed to extract the files into, in this case `locales`. Unfortunately, I'm not very familiar with C#, otherwise I would create a pull request.

**Comment by majordookie** [comment]
Same issue here, I would just download the portable version from [here](https://github.com/Battlelogium/Battlelogium/releases/download/2.2.11/Battlelogium2211.zip) and move it to your program files.

**Comment by RonnChyran** [comment]
The installer should be fixed now. If you have downloaded the portable version and would like desktop shortcut icons and the Control Panel uninstaller, just go into your Battlelog profile settings using Battlelogium (Hover over your Battlelog profile picture, click Settings), and click Force Update under Battlelogium Settings.
