### ISSUE TITLE
Can't be uninstalled

### ISSUE THREAD

**Issue by Stanzilla** [Battlelogium/Battlelogium#74]
When trying to uninstall via the Control Panel => Programs and Features panel, you get the following error message and uninstallation is not done.

![2015-09-23_23-02-04](https://cloud.githubusercontent.com/assets/75278/10058701/30b8f446-6247-11e5-918a-c88ccd70f868.png)

**Comment by rcolinray** [comment]
I'm having the same issue. Tried reinstalling the latest version but still unable to uninstall.

**Comment by rcolinray** [comment]
Possible workaround: Since the uninstaller just deletes all the files in *filelist* (everything in *C:/Program Files (x86)/Battlelogium), you can just delete the folder and then use an app like CCleaner to remove the entry from your list of programs.

**Comment by Stanzilla** [comment]
project is dead
