### ISSUE TITLE
cache folder gets enormus after time

### ISSUE THREAD

**Issue by ElPumpo** [Battlelogium/Battlelogium#83]
My battelogium cache folder located at `%appdata%Battlelogium` is 285mb, wtf? I guess I'd recommend other people to clean the folder too.

Not only that, but there's 2780 files inside the `cache` folder.
The folder is 11 months old for record.

Well it seems like the project is dead anyways...

**Comment by RonnChyran** [comment]
The new in-game UI solution is coming out as an official patch from DICE, so yeah, this is dead.

**Comment by ElPumpo** [comment]
Wait, there's a new ingame-UI server browser for BF4 / 3 too? (not only upcoming game?)

**Comment by RonnChyran** [comment]
The update is coming for BF4 as well. BF3 still uses Battlelog, which is
great because Battlelogium really only worked with BF3 in the first place.
BF4 support was always wonky for some reason.
